env:
  es6: true
  node: true
extends:
  - 'airbnb-base'
parser: '@babel/eslint-parser'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  requireConfigFile: false
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0